In [1]:
import numpy as np

list1 = [1, 2, 3, 4]
print(list1)
print(type(list1))

arry1 = np.array(list1)
print(arry1)
print(type(arry1))

[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
import random
import time
import numpy as np

a = []
for i in range(100000000):
    a.append(random.random())
print('随机完毕')

b = np.array(a)  # 转换为ndarray
print('转换完毕')



随机完毕
转换完毕


In [3]:
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

2.8568718433380127 1.8291430473327637


In [4]:
import numpy as np

list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)
print(list2) 

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


In [5]:
twoArray.tolist()

[[1, 2], [3, 4], [5, 6]]

In [6]:
list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
print(twoArray.ndim)

print(twoArray.shape)
print(twoArray.size)
print(twoArray.dtype)

2
(3, 2)
6
int64


In [7]:
four = np.array([[1, 2, 3], [4, 5, 6]])
print(four)

four1 = four
print(id(four))

[[1 2 3]
 [4 5 6]]
2155067575536


In [8]:
four.shape = (3,2)
print(id(four))
print(id(four1))
print(four)

2155067575536
2155067575536
[[1 2]
 [3 4]
 [5 6]]


In [9]:
four2 = four.reshape(2,3)
print(four)
print(id(four))
print(id(four2))

[[1 2]
 [3 4]
 [5 6]]
2155067575536
2155067575728


In [10]:
five = four.reshape((6,),order='F')
# f代表列展开 默认为c行展开
print(five)
six = four.flatten()
print(six)



[1 3 5 2 4 6]
[1 2 3 4 5 6]


In [22]:
seven = five.reshape(3,2)
print(seven)
seven

[[1 2]
 [3 4]
 [5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
t = np.arange(24)
print(t)
tt = t.reshape(3,8)
print(tt)

ttt = t.reshape(2,3,4)
print(ttt)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [26]:
a = np.array([9, 12, 88, 14, 25])

b = a.tolist()
print(b)

[9, 12, 88, 14, 25]


In [32]:
t1 = np.arange(24).reshape((6, 4))
print(t1)
print(t1+1)
print(t1+[1,2,3,4])
print(t1*2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]
 [13 15 17 19]
 [17 19 21 23]
 [21 23 25 27]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]


In [36]:
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((6, 4))
print(t1)
# print(t2)
# print(t1*t2)

print(t1*[1,2,3,4])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]
 [12 26 42 60]
 [16 34 54 76]
 [20 42 66 92]]


In [38]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(4).reshape((4, 1))
print(t2)
print(t1)
print(t1+t2)

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]]


In [40]:
a = np.arange(24).reshape((2, 3, 4))
b = np.arange(12).reshape((1, 3, 4))
print(a)
print(b)
a - b

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]])

In [41]:
# 联系轴
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("-" * 20)
print(np.sum(a, axis=0))  # [5 7 9]，按哪个轴求和，哪个轴没了
print("-" * 20)
print(np.sum(a, axis=1))  # [ 6 15]
print("-" * 20)
print(np.sum(a))
print("-" * 20)


[[1 2 3]
 [4 5 6]]
--------------------
[5 7 9]
--------------------
[ 6 15]
--------------------
21
--------------------


In [46]:
a = np.arange(24).reshape((2, 3, 4))
b = np.sum(a, axis=0)
print(a)
# print(b)
print("-" * 20)
print(b.shape)
print(b)
c = np.sum(a, axis=1)
print("-" * 20)
print(c.shape)
print(c)
d = np.sum(a, axis=2)
print("-" * 20)
print(d.shape)
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------
(3, 4)
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
--------------------
(2, 4)
[[12 15 18 21]
 [48 51 54 57]]
--------------------
(2, 3)
[[ 6 22 38]
 [54 70 86]]


切片

In [47]:
import numpy as np

a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[0], a)

# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

print(a[2:8:2])  #切片是左闭右开


0 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]


In [48]:
import numpy as np

t1 = np.arange(24).reshape(4, 6)
print(t1)
print('*' * 20)
print(t1[1])  # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*' * 20)
print(t1[1:])  # 取连续的多行
print('*' * 20)
print(t1[1:3, :])  # 取连续的多行
print('*' * 20)
print(t1[[0, 2, 3]])  # 取不连续的多行

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [49]:
t2 = np.arange(24).reshape(4, 6).tolist()
t2[[0, 2, 3]]

TypeError: list indices must be integers or slices, not list

In [51]:
print(t1)
print(t1[:, 1])  # 取一列
print('*' * 20)
print(t1[:, 1:])  # 连续的多列
print('*' * 20)
print(t1[:, [0, 2, 3]])  # 取不连续的多列
print('*' * 20)
print(t1[2, 3])  # # 取某一个值,三行四列  py是t1[2][3]
print('*' * 20)
print(t1[[0, 1, 1], [0, 1, 3]])  # 取多个不连续的值，[[行，行。。。],[列，列。。。]]

t1[1:3, 1:4]  #取1-3行，1-4列

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************
[0 7 9]


array([[ 7,  8,  9],
       [13, 14, 15]])

修改值

In [56]:
import numpy as np

t = np.arange(24).reshape(4, 6)
print(t)
print(id(t))
print('-' * 50)
# # 修改某一行的值
# t[1,:]=0
#
# # 修改某一列的值
# t[:,1]=0
#
# # 修改连续多行
# t[1:3,:]=0
#
# # 修改连续多列
# t[:,1:4]=0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:3,2:5]=0
#
# # 修改多个不相邻的点
t[[0,1],[1,3]]=0
print(t)

# 可以根据条件修改，比如讲小于10的值改掉
t[t<10]=0
print(t)
# 使用逻辑判断
# np.logical_and	& # np.logical_or	|
# np.logical_not		~
# t[(t>2)&(t<6)]=0	# 逻辑与，and
# t[(t<2)|(t>6)]=0	# 逻辑或，or
# t[~(t>6)]=0	# 逻辑非
# print(t)
t = t.clip(10, 18)
print(id(t))
t


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
2471051413808
--------------------------------------------------
[[ 0  0  2  3  4  5]
 [ 6  7  8  0 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
2471051423504


array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 18, 18, 18, 18, 18]])