In [2]:
import numpy as np
a = np.nan
b = np.inf
print(type(a))
print(type(b))

<class 'float'>
<class 'float'>


In [3]:
print(np.nan == np.nan)
print(True == 1)
print(False == 0)
np.nan + 1 

False
True
True


nan

In [6]:
t = np.arange(24, dtype=float).reshape(4, 6)

t[2,3] = np.nan
t[3,3] = np.nan
print(t)

np.count_nonzero(t!=t)

t[np.isnan(t)] = 0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. nan 16. 17.]
 [18. 19. 20. nan 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14.  0. 16. 17.]
 [18. 19. 20.  0. 22. 23.]]


In [21]:
t = np.arange(24, dtype=float).reshape(4, 6)

t[2,3] = np.nan
t[3,3] = np.nan
print(t)

# t[np.isnan(t)] = t.mean()

print(t.shape[1])
# 轴1的长度
print('-'*50)
for i in range(t.shape[1]):
    temp_col = t[:,i]
    # temp_col是每一列
    # print(temp_col)
    nan_num = np.count_nonzero(temp_col != temp_col)
    # nan_num是每一列nan的个数
    # print(nan_num)
    if nan_num != 0:
        temp_col_not_nan = temp_col[temp_col == temp_col] #存在nan的列里面非nan的值组成的array
        print(temp_col_not_nan)
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)
print('-'*50)
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. nan 16. 17.]
 [18. 19. 20. nan 22. 23.]]
6
--------------------------------------------------
[3. 9.]
--------------------------------------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14.  6. 16. 17.]
 [18. 19. 20.  6. 22. 23.]]
