In [3]:
import numpy as np

a = np.arange(24).reshape(4,6)
print('原来数组：')
print(a)
print('-'*50)

print('改变后：')
print(np.transpose(a))
#对换 在二维相当于转置 在高纬可以按指定顺序排列多个轴

a = np.arange(24).reshape(4,6)
print(a.T) #转置

原来数组：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
改变后：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [4]:
t1 = np.arange(24).reshape(4, 6)
ret1 = t1.swapaxes(1,0)
#二维相当于转置了
print(t1)
print(ret1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [5]:
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
print('-' * 50)
t3 = np.swapaxes(t3, 1, 2)
# 交换两个轴 不能同时操作多个轴
print(t3.shape)

(3, 4, 5)
--------------------------------------------------
(3, 5, 4)


In [6]:
a = np.ones((3, 4, 5, 6))
# np.rollaxis(a, 2).shape
b = np.rollaxis(a, 3, 1)
#将原先轴3 放到原先轴1之前 轴1及之后依次后移
print(b.shape)

(3, 6, 4, 5)


In [7]:
print(b.shape)
c=np.rollaxis(b, 1,4)  #轴会滚动，直到它位于此位置之前
print(c.shape)

(3, 6, 4, 5)
(3, 4, 5, 6)
